- name: Install Apache On Centos 7
  hosts: web
  tasks:
    - name: Installing PHP packages
      yum:
        name: ['php', 'php-fpm', 'php-cli', 'php-curl', 'php-mysqlnd', 'php-zip', 'php-mbstring', 'php-devel']
        state: present
        enablerepo: remi-php81
    - name: Apache web installaion package started
      yum:
        name: httpd
        state: latest
    - name: copying file controller to target host
      copy:
        src: ./code
        dest: /var/www/html
        owner: apache
        group: root
        mode: 0755
    - name: copy index file to web host
      copy:
        src: ./cfg/index.html
        dest: /var/www/html
        owner: apache
        group: root
        mode: 0755
    - name: Restart apache service
      service:
        name: httpd
        state: restarted
    - name: Apache service enabled
      service:
        name: httpd
        enabled: yes
    - name: Open firewall port for apache
      firewalld:
        port: 80/tcp
        state: enabled
    - name: start apache service again for ensure
      service:
        name: httpd
        state: restarted

