- name: Install mariadb server on Target
  hosts: db
  tasks:
    - name: Installing Python mysqld Package
      yum:
        name: python3-PyMySQL
        state: present
    - name: Installing Maria DB Package
      yum:
        name: mariadb-server
        state: present
    - name: Starting DB Service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Mysql Client Installing
      yum:
        name: mysql
        state: present
